version: "3.5"
services:
  operator:
    build:
      context: operator
      args:
        UPSTREAM_VERSION: v1.2-testnet
    image: "safestake-testnet.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
